### PR TITLE
Fix keeps changing oh-my-zsh last_working_dir

### PR DESCRIPTION
**Pull request by mracos**
# Summary

Fix keeps changing oh-my-zsh last_working_dir

Fixes: #255

### CODE REVIEW

**Comment by Stratus3D** [comment]
Thanks for the PR @mracos ! Is there any way we could do this without using `readlink -m`? `readlink` doesn't support that option on OSX.

I need to figure out why tests didn't catch this.

**Comment by mracos** [comment]
As I don't have a mac I do not know how to test it.
But maybe we can just do `dirname $current_script_path` (but i don't know the implications and the bugs that this bring or some workaround with `pushd && popd`
what do you say? :thinking:

**Comment by mracos** [comment]
Even commenting out the ASDF_DIR="$(dirname..." line makes all the tests pass, is that right?

**Comment by trs** [comment]
Related: https://github.com/asdf-vm/asdf/pull/280

**Comment by Stratus3D** [comment]
I believe this issue has been fixed in https://github.com/asdf-vm/asdf/pull/334. `cd` is no longer used in the subshell.

**Pull request closed without merging**
