### PR TITLE
Prepare for 0.2.1 release.

### PR DESCRIPTION
**Pull request by Stratus3D**
We've had a lot of bugfixes over the last month, so I figured it's about time to tag another patch version. I don't see anything here that would break the existing 0.2.0 API, so I think it's safe to just increment the patch version. With some of the upcoming changes there will likely be some API differences, so the next release after this one will probably be 0.3.0.

I'm going to wait until #135 is merged before merging this. Once this is merge I'll tag v0.2.1.

### CODE REVIEW

**Comment by Stratus3D** [comment]
Updated the README and utils.sh with the new version too.

**Comment by tuvistavie** [comment]
Thanks! I think it is indeed a good idea to release a new version.
If we are sure that #139 does not affect a significant number of users, I think we can merge this!

**Comment by Stratus3D** [comment]
I'm going to go ahead and merge this. I don't think #139 affects many users. If it does turn out to be a common issue we can add a warning to asdf and tag 0.2.2.

**Comment by tuvistavie** [comment]
Great, thanks! :+1:

**Pull request merged**
