### PR TITLE
Enable Windows tests on GitHub Actions

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
The tests still fails, but it has nothing to do with this PR.

**Comment by imbsky** [comment]
and after merging this PR, we will need to be removed appveyor integration from the organization settings.

**Comment by vic** [comment]
Yep, those appveyor builds have been always failing, I'm ok with removing them (or perhaps making the windows part of the workflow optional).

Perhaps someday, someone with access to windows can help us get those test pass.

**Comment by imbsky** [comment]
I changed config to ignore the tests failure on Windows.

**Comment by imbsky** [comment]
Okay, maybe this is ready for review now.

**Comment by imbsky** [comment]
Oh, I really don't like yaml and the editor that can't handle it well.

**Comment by vic** [comment]
Thanks 👍

**Comment by imbsky** [comment]
👍

**Comment by vic** [comment]
FYI @abhishalya, this MR removes the appveyor build introduced in  #450 since we are now able to test on all platforms with github actions. Test were never successful on windows since #450 was merged some months ago.

Windows tests are run now, but being ignored til someone really finds the motivation to get them passing. 

@HashNuke, @Stratus3D we need to disable the appveyor integration in this repo (I dont have access to such settings), could anyone do that, please?

**Comment by imbsky** [comment]
There is probably an appveyor item somewhere in these links, and deleting it should solve the problem.
https://github.com/asdf-vm/asdf/settings/installations
https://github.com/organizations/asdf-vm/settings/oauth_application_policy
https://github.com/organizations/asdf-vm/settings/installations

**Comment by abhishalya** [comment]
@vic Thanks for updating me. @jayvdb maybe you want to look into this?

**Comment by Stratus3D** [comment]
Thanks @imbsky. I just uninstalled AppVeyor.

**Comment by imbsky** [comment]
👍

**Pull request merged**
