### PR TITLE
fix: rename internal function `asdf_tool_versions_filename`

### PR DESCRIPTION
**Pull request by hyperupcall**
# Summary

Applied suggestions from [here](https://github.com/asdf-vm/asdf/pull/1485#discussion_r1164088836) and [here](https://github.com/asdf-vm/asdf/pull/1518#discussion_r1159820722).

### CODE REVIEW

**Review by jthegedus — APPROVED** [review]
LGTM

**Comment by jthegedus** [comment]
@Stratus3D are you happy with these changes?

**Review by jthegedus — APPROVED** [review]
I know this is annoying, but can we have two PRs for these changes.

One with the rename, the other with the improved nullglob change?

The PR titles end up in the Changelog so we would ideally like PRs with one change so we can name the PRs and therefore changelog better.

**Review by jthegedus — CHANGES_REQUESTED** [review]
I know this is annoying, but can we have two PRs for these changes.

One with the rename, the other with the improved nullglob change?

The PR titles end up in the Changelog so we would ideally like PRs with one change so we can name the PRs and therefore changelog better.

**Review by jthegedus — APPROVED** [review]
Thanks mate!

**Comment by Stratus3D** [comment]
Looks good to me!

**Pull request merged**
