### PR TITLE
fix: make asdf latest output consistent

### PR DESCRIPTION
**Pull request by cj81499**
# Summary

Modify the default query used by `asdf latest` to allow for "v" prefixes.

Additionally, perform a small refactor to extract some duplicated logic to a helper function.

Fixes: #1684

## Other Information

I believe that `asdf latest --all` uses an empty query (it simply doesn't pass a query argument), which is different than `asdf latest <plugin>`.
I think both should use the same default query, but I'm not sure which (`"v?[0-9]"` vs `""`) should be preferred. I'd like guidance on which should be preferred.

### CODE REVIEW

**Comment by cj81499** [comment]
I'm having trouble reproducing the test failures locally (in fact, I'm having trouble getting a clean run of the tests on the default branch).

I'd appreciate help getting the tests running/passing.

**Comment by hyperupcall** [comment]
The tests that usually fail are in `update_command.bats`. When I run `bats test`, 5 tests fail out of 368:

```text
update_command.bats
 ✓ asdf update --head should checkout the master branch
 ✗ asdf update should checkout the latest non-RC tag
   (in test file test/update_command.bats, line 41)
     `[ "$status" -eq 0 ]' failed
   Cloning into '/tmp/asdf.UZh0/home/.asdf'...
   done.
 ✗ asdf update should checkout the latest tag when configured with use_release_candidates = yes
   (in test file test/update_command.bats, line 54)
     `[ "$status" -eq 0 ]' failed
   Cloning into '/tmp/asdf.OpSy/home/.asdf'...
   done.
 ✓ asdf update is a noop for when updates are disabled
 ✓ asdf update is a noop for non-git repos
 ✓ asdf update fails with exit code 1
 ✗ asdf update should not remove plugin versions
   (in test file test/update_command.bats, line 85)
     `[ "$status" -eq 0 ]' failed
   Cloning into '/tmp/asdf.RWrB/home/.asdf'...
   done.
 ✗ asdf update should not remove plugins
   (in test file test/update_command.bats, line 95)
     `[ "$status" -eq 0 ]' failed
   Cloning into '/tmp/asdf.dOCk/home/.asdf'...
   done.
 ✗ asdf update should not remove shims
   (in test file test/update_command.bats, line 106)
     `[ "$status" -eq 0 ]' failed
   Cloning into '/tmp/asdf.n4EO/home/.asdf'...
   done.
```

If you get other failures that aren't due to your changes, it might be useful to file an issue about that.

**Comment by Stratus3D** [comment]
Hi @cj81499 thanks for the PR, these look like good changes. I'm sorry I was not able to review sooner. I have rewritten asdf in Golang and I believe I fixed this issue. The regex for latest version is now defined in a single place in the `versions` package - https://github.com/asdf-vm/asdf/blob/3a9912e839b0cc68ce4886a0365eaef3b7f9ab7e/internal/versions/versions.go#L27. I'm going to close this PR as I don't think it makes sense to merge now.

**Comment by cj81499** [comment]
I don't use `asdf` much anymore, so that's fine. fwiw, if this is fixed, you probably want to close #1685 :)

**Pull request closed without merging**
