### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by wulfmann**
# Summary

Made a few changes to the readme to include the homebrew explanation, and separate installation and set up.

Fixes: #396

### CODE REVIEW

**Comment by jthegedus** [comment]
Thanks for your help :100:

**Comment by d4rky-pl** [comment]
The setup instructions are incorrect - the Homebrew formula installs things a bit differently.
The paths (in case of Bash) are:

```
. /usr/local/opt/asdf/asdf.sh
. /usr/local/opt/asdf/etc/bash_completion.d/asdf.bash
```

**Comment by Stratus3D** [comment]
@d4rky-pl can you open up a new issue for that?

**Comment by d4rky-pl** [comment]
@Stratus3D [sure thing!](https://github.com/asdf-vm/asdf/issues/425)

**Pull request merged**
