### PR TITLE
fix: asdf not working when bin is symlinked

### PR DESCRIPTION
**Pull request by cornfeedhobo**
# Summary

This PR seeks to add support for resolving `asdf_dir` when `bin/asdf` is symlinked to a non-standard location.

Fixes: #1657

### CODE REVIEW

**Comment by hyperupcall** [comment]
Thanks for working on a fix! - although these changes fix the `source`ing issues, `asdf` will still break in subtle ways because full setup depends on an `asdf` function loaded into the shell. And with this solution, the user doesn't know that they failed to load the `asdf` function in the shell. Although the errors are fixed, it is misleading because the user will get errors elesewhere.

I think a better solution would be to warn if the user has not sourced `asdf.sh` (or `asdf.fish`, etc.), and exit completely. That will fix the hard to understand `source` errors and give the user direct instructions on how to properly fix the issue

**Comment by cornfeedhobo** [comment]
@hyperupcall continuing the thread here..

> It would be good to print a warning (and exit) in this case

When checking for `realpath` or `readlink` support, I can have the final condition test if the directory has the expected structure or error out saying that symlink support doesn't work without those tools. I kind of already did, but it's simplistic in it's current form.

**Comment by cornfeedhobo** [comment]
> will still break in subtle ways

I don't see how.

- All functions in `asdf` are called by asdf itself, so the subshell is already loaded correctly
- If plugins are currently written to be naive and not use `asdf_dir`, then how would they break from this?
- This doesn't alter the location that plugins are installed or how they are managed, so any logic based on `dirname $0` should still work.

Could you give an example of where you expect this would break? Maybe I can test it out or something?

**Comment by hyperupcall** [comment]
I don't think having the `realpath` or `readlink` code is a good idea. For each shell, we already [have logic](https://github.com/asdf-vm/asdf/blob/master/asdf.sh) to calculate the correct directory paths and stuff. The `realpath` stuff seems extraneous. And I'm not sure directory check you mentioned will catch the case that the user has not sourced the equivalent of `asdf.sh` for their shell. 

Instead, I was thinking of having some `ASDF_INTERNAL_FUNCEXEC` that we always pass into the `bin/asdf.sh` from the shell functions. In `bin/asdf.sh`, if that environment variable is not present, then we print the error. This seems like the most simple solution

**Comment by hyperupcall** [comment]
> I don't see how.

There are various commands that set [an environment variable in the user's current interactive shell](https://github.com/asdf-vm/asdf/blob/4085e5542bac824ea124610ad247c2f90d1b8d93/asdf.sh#L137). Unfortunately, I think this would make your approach a no-go since this case would be impossible to handle since no logic would be ran in the user's interactive shell environment.

**Comment by cornfeedhobo** [comment]
I see. That's truly unfortunate. `asdf`'s internal management of updates and the non-standard loading are the only things blocking adoption of this tool. I keep revisiting this every few years wondering when I'll be able to ditch the `*env` suite I've been using.

**Comment by hyperupcall** [comment]
It is unfortunate - if #1164 is fixed, then perhaps we would move forward with something like this thenceforth.

**Pull request closed without merging**
