### PR TITLE
chore: question Issue type & direct to GH Discussions

### PR DESCRIPTION
**Pull request by jthegedus**
# Summary

This will add an option in the New Issue selection (https://github.com/asdf-vm/asdf/issues/new/choose) to select a "question" type which will direct people to our GitHub Discussions

The goal being reduction in Issues that are merely questions/clarifications.

### CODE REVIEW

**Comment by jthegedus** [comment]
Perhaps this should link out to StackOverflow instead? :thinking:

**Comment by jthegedus** [comment]
Merging, we can change to SO later if desired.

**Comment by jthegedus** [comment]
This is the result.

image

**Comment by Stratus3D** [comment]
> Perhaps this should link out to StackOverflow instead? 🤔

it would be nice if we could link to both. Some users may prefer StackOverflow, and I follow asdf questions on both sites.

**Pull request merged**
