### PR TITLE
Add tests for code in asdf.fish

### PR DESCRIPTION
**Pull request by Stratus3D**
# Summary

Write unit tests for code in asdf.fish.

Fixes: #286

### CODE REVIEW

**Comment by Stratus3D** [comment]
Looks like Travis CI doesn't have fish shell installed.

**Comment by danhper** [comment]
@Stratus3D  Here is the script I use to install fish on Travis:
https://github.com/danhper/fundle/blob/master/prepare-ci.sh
Let me know if you would like me to help.

**Comment by Stratus3D** [comment]
Thanks @danhper , I created a script for setting up Travis and got all but one of the asdf.fish tests passing on Travis. They all passed for me locally, and I tried several things and eventually gave up on getting it to pass on Travis, so I commented it out. The other three tests passed on Travis.

**Comment by danhper** [comment]
Thanks a lot for working on this. Looks good to me!

I found the issue. It seems that `status -f`, which is used to set `ASDF_DIR`, is very naive and returns the current filename as given to fish. This means that if we call `source asdf.fish`, `status -f` will return `./asdf.fish`. Therefore, `ASDF_DIR` will become `.`. It then appends `./bin` to the path and the `grep` fails.
I believe it works in your environment because `$HOME/.asdf/shims` exist. `ASDF_DATA_DIR` will default to `$HOME/.asdf` and `$HOME/.asdf/shims` will therefore be added to the path, making `grep` succeed.

I just pushed the fix to this branch. Please merge if it looks good.

**Comment by Stratus3D** [comment]
Awesome! Thanks for fixing that test.

**Pull request merged**
