### PR TITLE
appveyor.yml: Add support for Windows

### PR DESCRIPTION
**Pull request by abhishalya**
# Summary

This adds support for windows through Appveyor CI.

Closes https://github.com/asdf-vm/asdf/issues/450

### CODE REVIEW

**Comment by abhishalya** [comment]
I ran it, you can have a look at https://ci.appveyor.com/project/abhishalya/asdf

I guess the failure is because of something mentioned [here](https://github.com/sstephenson/bats/pull/234). Hope there is a workaround.

**Comment by jayvdb** [comment]
Everyone there is saying migrate to https://github.com/bats-core/bats-core . It should be compatible, so you could try just using that instead here.

If you find it isnt ompatible, create a new PR to upgrade the test suite to bats-core, then return to this after it is merged.

**Comment by abhishalya** [comment]
@jayvdb The bats seems to be working now, but the tests fail unfortunately.

**Comment by jayvdb** [comment]
I've done a build without the `rm`'s at https://ci.appveyor.com/project/jayvdb/asdf/builds/22070158

- install_command.bats : 5/11 errors, 2 being caused by `../.asdf/shims/dummy: No such file or directory`
- plugin_list_all_command.bats : 1/1 not ok
- remove_command.bats: 1/6 not ok
- reshim_command.bats: 4/4 not ok
- uninstall_command.bats: 4/7 not ok
- update_command.bats: 4/6 not ok
- utils.bats: 3/34 not ok
- version_commands.bats: 4/27 not ok
- which_command.bats 5/5 not ok

Therefore the best cost:benefit for getting more tests operation is in debugging failures in utils.bats and version_commands.bats .

One of the biggest problems which is easy to fix is that in your test environment `find` is `/c/Windows/system32/find`, so these two lines are probably failing:

```console
> git grep 'find ' lib
lib/commands/which.sh:        location=$(find -L "$full_executable_path" -maxdepth 4 -name "$command" -type f -perm -u+x | sed -e 's|//|/|g')
lib/utils.sh:  find_result=$(find "$update_file_dir" -name "$update_file_name" -type f -mtime +1 -print)
```

So set up your test environment so find is a GNU find.  Probably similar problems exist with other executables.

**Comment by abhishalya** [comment]
@jayvdb Just one test failing now.

**Comment by Stratus3D** [comment]
@abhishalya thanks for all your work on this. I've fallen behind when it comes to reviewing PRs recently. I think it would be nice to be able to support Windows, at least to some degree.

I just updated our build to use the `bats-core/bats-core` fork of BATS, version 1.1.0. Feel free to rebase your branch onto master if you think that would be helpful.

**Comment by Stratus3D** [comment]
Sorry, I guess rebasing wouldn't help since I only changed the Travis build for Linux and OSX. Disregard that part of my last comment.

**Comment by abhishalya** [comment]
@Stratus3D Can you have a look at the [build log](https://ci.appveyor.com/project/abhishalya/asdf), there was just one failing test. Maybe you can help me fill the environment difference between the Linux and Windows.

```
not ok 55 asdf exec should pass all arguments to executable even if shim is not in PATH
# (in test file test/shim_exec.bats, line 42)
#   `[ "$output" == "" ]' failed
```

**Comment by Stratus3D** [comment]
I see the failure. I will look at that test tonight and see if I can figure out what it's doing differently. I remember coming across an invalid test when working on https://github.com/asdf-vm/asdf/pull/520.

**Comment by abhishalya** [comment]
@Stratus3D Can you have a look at this again :)

**Comment by Stratus3D** [comment]
@abhishalya sorry for the late reply. I'm going to go ahead and merge this PR so we can get this config on the master branch. We may still have some issues to work through, but I think it's good to have builds running on windows. Thanks for all your work on this!

**Comment by jayvdb** [comment]
Well done @abhishalya !

**Pull request merged**
