### PR TITLE
fix: create install directory with `mkdir -p`

### PR DESCRIPTION
**Pull request by vespian**
# Summary

Issue with jq pluging being [moved](https://github.com/AZMCode/asdf-jq/issues/8) showed an issue in asdf itself - an empty download dir can be created:

```
dev@pr-mr-test:~/$ tree /home/dev/.asdf/downloads/
/home/dev/.asdf/downloads/
├── jq
│   └── 1.6
```

This was causing asdf to fail with cryptic message:
```
mkdir: cannot create directory ‘/home/dev/.asdf/downloads/jq/1.6’: File exists
```

This MR fixes that.

### CODE REVIEW

**Comment by hyperupcall** [comment]
LGTM! Surprised that this flag wasn't already present.

**Review by jthegedus — APPROVED** [review]

**Comment by jthegedus** [comment]
I too am surprised this wasn't already present, thanks!

**Comment by zoeytruong** [comment]
Thank you for fixing this. Can this merged PR go into the next release? The current release `v.0.11.3` does not have this fix. I will really appreciate your help.

**Comment by hyperupcall** [comment]
@zoeytruong Yes! It's not in `v0.11.3`, but it's slated for inclusion in `v0.12.0`. The only issue that's really blocking the release is #1550, but #1560 should be merged relatively soon. Once it's merged I think the asdf team will make their next release

**Pull request merged**
