### PR TITLE
Get version from env if ASDF_${TOOL}_VERSION is defined.

### LINKED ISSUE #49: [improvement] shell command
there are local and global commands that give you ability to set local or global version however sometimes we need to temporary set version for currently running shell session. 
So what I propose is addition of shell command

### PR DESCRIPTION
**Pull request by vic**
For example if asdf finds that the `ASDF_FOO_VERSION` is
defined in the current environment it will override the
version of `foo` from the `.tool-version` file.

Closes #49

### CODE REVIEW

**Comment by HashNuke** [comment]
@vic Thanks for the fix. I'll try this out tonight and merge it.

**Comment by tuvistavie** [comment]
I just noticed this PR was still opened.
@asdf-vm/maintainers I think we can merge, wdyt?

**Comment by vic** [comment]
@tuvistavie rebased this PR on current master.

**Comment by vic** [comment]
merging this :)

**Pull request merged**
