### PR TITLE
Ensure install commands always add asdf loading code on a new line in bashrc.

### LINKED ISSUE #98: -bash: asdf: command not found
I made all steps - installed all packages for Mac OS and updated `.bash_profile`, but have:

>  -bash: asdf: command not found

### PR DESCRIPTION
**Pull request by Stratus3D**
This could fix #98. @HashNuke what do you think? Good solution or ugly hack?

### CODE REVIEW

**Comment by BenMorganIO** [comment]
I think those quotes have to be changed to double quotes. This broke on an Ubuntu machine during a copy and paste of those lines.

**Comment by Stratus3D** [comment]
@BenMorganIO Good catch, it looks like the `-e` flag is required. Double quotes don't seem to have any effect (at least on CentOS and OSX). I'll test on Ubuntu tonight.

**Comment by Stratus3D** [comment]
@BenMorganIO Just merged that PR. Want to give it a try on Ubuntu?

**Comment by BenMorganIO** [comment]
@Stratus3D works like a charm! :D

**Pull request merged**
