### PR TITLE
fix: excludes "milestone" releases in "latest" command

### PR DESCRIPTION
**Pull request by log2**
# Summary

Fixes: https://github.com/asdf-vm/asdf/issues/1306

### CODE REVIEW

**Comment by jthegedus** [comment]
This is a minor change that I don't think it will hurt anyone, however we want to encourage plugin authors to implement their own `bin/latest-stable` script which you can see is called 9 lines above this change. Docs: https://asdf-vm.com/plugins/create.html#bin-latest-stable

**Comment by log2** [comment]
I've added [PR](https://github.com/rfrancis/asdf-gradle/pull/11) to asdf-gradle project, as promised, @jthegedus

**Review by Stratus3D — APPROVED** [review]
I'm fine with the changes here but the existence of this code bothers me the in the same way as the PR I was reviewing earlier - https://github.com/asdf-vm/asdf/pull/1191#discussion_r929074452

**Comment by Stratus3D** [comment]
Thanks for the PR @log2 ! Sorry for the late review.

**Pull request merged**
