### PR TITLE
fix: use universal scope for fish_user_paths in fish shell integration

### PR DESCRIPTION
**Pull request by bakotaco**
# Summary

This PR addresses issue described in #1629. Currently the Fish shell setup script sets fish_user_paths as a global variable.  This conflicts with the expected universal nature of fish_user_paths, leading to path assignments not persisting across sessions when using fish_add_path.

Fixes:
- fish-shell/fish-shell#9819
- #1629

## Other Information

This ensures that any paths added via fish_add_path are retained across all Fish shell sessions, aligning with the standard behavior of fish_add_path as outlined in its [documentation](https://fishshell.com/docs/current/tutorial.html).

### CODE REVIEW

**Review by jthegedus — APPROVED** [review]
Looks good to me, thanks!

**Comment by jthegedus** [comment]
And of course when I have the time to go through PRs for the first time this year GitHub "experiences issues". Will merge tomorrow. Cheers!

**Comment by jthegedus** [comment]
There seem to be some other fish issues, but we can deal with them separately :+1:

**Comment by hyperupcall** [comment]
This MR is a breaking change in cases where a user uses `asdf` in a script, as shown by the failing tests. Because `--universal-` persists the variable modification, there needs to be better isolation for the fish test as well.

**Comment by jthegedus** [comment]
> This MR is a breaking change in cases where a user uses `asdf` in a script, as shown by the failing tests. Because `--universal` persists the variable modification, there needs to be better isolation for the fish test as well, which wasn't done either.

Yeah, I would like to get this fixed before performing a new release. Help welcome as my environment is currently unable to run fish without significant effort :sweat_smile:

**Comment by bakotaco** [comment]
apologies, but after talking to @faho (long time fish contributor) I came to the conclusion this was actually an incorrect fix... I created a followup PR with a proper fix and explanation: #1709

**Pull request merged**
