### PR TITLE
Readme: format install instructions better

### PR DESCRIPTION
**Pull request by rstacruz**
# Summary

Update install instructions on the Readme to make it easier to understand :heart:

> image

## Other Information

I'd like to propose adding Fish + Fisherman integration via https://github.com/rstacruz/fish-asdf — but I figured it'd be best to clean this part up before adding more variants in.

### CODE REVIEW

**Comment by vic** [comment]
Hey, thanks for taking the time to improve the README. And yes, separating the code snippets for each shell variant is nicer as people can just copy the one they need. Could you just resolve the conflict and we could merge this.

Regarding fish, we could have a link to your fish plugin, I'm not very sure as what difference/improvements does the plugin has over the fish scripts we currently have. If your plugin renders our scripts obsolete, we could remove them, @tuvistavie opinions on this?

**Comment by tuvistavie** [comment]
Thank you for the changes, I think this is indeed simpler for new users.

> If your plugin renders our scripts obsolete, we could remove them, @tuvistavie opinions on this?

I think we should keep things as is for this part.
There are many different plugin managers for all shells, so I would rather keep asdf plugin manager agnostic, and keep the necessary files in the asdf repository so that anyone can use asdf without the need for other external tool or plugin.
If people want to write wrappers or plugins for asdf, this is of course very welcome, and we could maybe have a page in the wiki for these kind of contributions (I do have a plugin for fish too https://github.com/tuvistavie/fish-asdf), but I think it should not be part of asdf itself.

**Comment by rstacruz** [comment]
> Regarding fish, we could have a link to your fish plugin, I'm not very sure as what difference/improvements does the plugin has over the fish scripts we currently have. 

Modifying your config files is not a good idea if you're using [fisherman](http://fisherman.github.io/).

**Comment by rstacruz** [comment]
Conflicts resolved! btw this PR doesn't include `fish-asdf`, it's still the same info in the readme just reformatted.

**Comment by tuvistavie** [comment]
Thank you!

**Pull request merged**
