### PR TITLE
docs: update git/bash install docs to use 0.9.1

### PR DESCRIPTION
**Pull request by myersg86**
Branch 0.8.1 no longer exists, leading to detached head upon checkout

# Summary

Fixes: List issue numbers here

### CODE REVIEW

**Comment by jthegedus** [comment]
Thanks for raising this. I noticed this issue but haven't had the time to debug why https://github.com/asdf-vm/asdf/blob/master/.github/workflows/docs-version.yml didn't work on the `0.9.x` releases and update itself. It would be better to investigate why that didn't trigger than manually update the version.

**Comment by Taytay** [comment]
To be honest, I found it a bit strange that the recommended way to install asdf was to install a particular branch in the first place. I dutifully followed it, but then I ran `asdf update` and discovered that there was actually a more recent version (0.9.0. This made me wonder if our machine setup scripts would be out of date if they referred to a particular branch of asdf as the docs recommended. Shouldn't the docs just tell people to install the latest from the default branch, since presumably that is the most recent stable version?

**Comment by Stratus3D** [comment]
> To be honest, I found it a bit strange that the recommended way to install asdf was to install a particular branch in the first place. I dutifully followed it, but then I ran `asdf update` and discovered that there was actually a more recent version (0.9.0. This made me wonder if our machine setup scripts would be out of date if they referred to a particular branch of asdf as the docs recommended. Shouldn't the docs just tell people to install the latest from the default branch, since presumably that is the most recent stable version?

No, the latest default branch is not considered stable. The standards for a tagged release are a bit higher, and we expect most users to be using a tagged release and not latest default (though us maintainers often do use latest default most of the time). The docs should instruct users to install the latest tag, and as seen here we've got a bug somewhere that isn't bumping the version in the docs. 

We instruct users installing via git to install a specific **tag**, not a specific **branch**, the git flag for doing so happens to be `--branch`, which is a bit confusing.

**Review by Stratus3D — APPROVED** [review]

**Comment by Stratus3D** [comment]
I went ahead and merged this to prevent users from continuing to install the old version.

**Comment by ksmolnicki** [comment]
But the v0.9.1 branch/tag is still missing

**Pull request merged**
