### PR TITLE
Add Idris plugin

### PR DESCRIPTION
**Pull request by vic**
[plugin](http://github.com/vic/asdf-idris) for installing [Idris](http://idris-lang.org)

### CODE REVIEW

**Comment by Stratus3D** [comment]
Another plugin! Yay!

**Comment by Stratus3D** [comment]
Actually, it looks like two of the build jobs are failing and only one is succeeding. It looks like the error is due to the `idris` command not being found.

**Comment by vic** [comment]
@Stratus3D  Yeah, i'm working on it, the one succeeding is just installing the OSX binary, the other two are building Idris with cabal (once on linux and other on osx), and it's taking lots of time, so I'm trying to get those tests green.

**Comment by vic** [comment]
@Stratus3D  Yay, we are finally green !  

but look at how much time it takes to build from source:

https://travis-ci.org/vic/asdf-idris/builds/179768882

**Comment by Stratus3D** [comment]
Wow. I'm not surprised though. At least it's automated :)

**Pull request merged**
