### PR TITLE
update setup documentation for zsh and homebrew

### PR DESCRIPTION
**Pull request by FlorinSenoner**
Minor update the setup documentation for zsh and homebrew users. Hope this makes it easier for some people in the future to add the correct lines to their `~/.zshrc` file

### CODE REVIEW

**Comment by Stratus3D** [comment]
Thanks for the PR! My only concern here is that we've got quite a bit of duplication. I wonder if we could reorganize things here so we don't have to repeat the paragraph on Homebrew completions.

**Comment by olets** [comment]
Fwiw I like the duplication. If it was code it'd be nice to condense it more, but a given reader is going to be in one tab or the other

**Comment by jthegedus** [comment]
It might be time for us to split out the shared contents of the tabs into their own .md files and use the [Docsify include feature](https://docsify.js.org/#/embed-files?id=embed-files). Just a suggestion. It can get unwieldy as well, but probably less so than the duplication

**Comment by danhper** [comment]
Sorry, I just realized this PR was opened. I merged #537, which was doing mostly the same thing, so I will close this one.
Thanks again!

**Pull request closed without merging**
