### PR TITLE
fix(nushell): Use `def --env` instead of `def-env`

### LINKED ISSUE #1609: bug: Deprecated Call 'let-env' in asdf.nu
### Describe the Bug

It appears that the let-env call, which is currently used on asdf.nu and in the script to configure the config.nu, has been deprecated. As a result, an error message is displayed when using ASDF. To address this issue, I will open a pull request to resolve the deprecation of the let-env call and ensure that ASDF continues to function properly.

### Steps to Reproduce

Follow the instructions in the `Nushell & Git` [documentation](https://asdf-vm.com/guide/getting-started.html).

### Expected Behaviour

ASDF should work correctly, without any error messages:
image

### Actual Behaviour

The following error message is shown: `let-env' is deprecated`
image

### Environment

```shell
OS:
Linux windows 5.15.90.3-microsoft-standard-WSL2 #1 SMP Wed Jul 12 00:26:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
0.83.1

BASH VERSION:
5.1.16(1)-release

ASDF VERSION:
v0.12.0-624604a

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/home/heiytor/.asdf
ASDF_DIR=/home/heiytor/.asdf
ASDF_CONFIG_FILE=/home/heiytor/.asdfrc

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 4f8aa3d
python                       https://github.com/danhper/asdf-python.git master 8505457
rust                         https://github.com/code-lever/asdf-rust.git master 95acf4f
```

### asdf plugins affected (if relevant)

_No response_

### LINKED ISSUE #1680: bug: nushell `def-env` is deprecated
### Describe the Bug

Version 0.87 of nushell deprecates the use of `def-env` nushell/nushell#10715. It will be removed in the next version.

This is the only place where it's used: https://github.com/asdf-vm/asdf/blob/fad23bc9f4d38747f28d6708ab01689749030063/asdf.nu#L1

AFAIK just replacing it with `def --env` should work.

### Steps to Reproduce

Just use asdf from nushell.

### Expected Behaviour

No deprecation warnings should be issued with version 0.87.

### Actual Behaviour

Deprecation warnings with version 0.87.

### Environment

```shell
Not relevant.
```

### asdf plugins affected (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by hyperupcall**
# Summary

Nushell recently deprecated use of `def-env`. Migration is clear. [This](https://github.com/nushell/nushell/pull/10715) issue implements the deprecation and [this](https://github.com/nushell/nushell/pull/10566) issue implements `def --env`. It states:

> Because `def-env` is used everywhere, including virtualenv, I propose the following steps:
>
> - 0.86: Add this PR, keep `def-env` and `extern-wrapped` unchanged.
> - 0.87: Add deprecation warning to `def-env` and `extern-wrapped` but keep them working.
> - 0.88 (or later): Remove `def-env` and `extern-wrapped`.

So, the minimum version needs to be bumped to 0.86. Unfortunately, this means older versions will no longer be support, but it is difficult as nushell has many backwards incompatible changes being made

Current version of nushell is [0.87.0](https://github.com/nushell/nushell/releases/tag/0.87.0), which was released last week. To ensure this fix gets merged before the release of 0.88.0, it __should be merged before ~December 13__

Closes #1680
Closes #1700

### CODE REVIEW

**Comment by hyperupcall** [comment]
@jthegedus @Stratus3D this is an urgent bugfix. When the latest version of nushell is released in a few weeks, asdf will break without this patch.

**Comment by acidghost** [comment]
@jthegedus @Stratus3D ping.

Nushell 0.88 has been released with `def-env` removed, meaning that asdf cannot be used from nushell.
Can you please merge this PR and release a new version of asdf?

**Comment by hyiltiz** [comment]
This is a minimal change that has no impact to any part of asdf core mechanics and only updates asdf autocomplete interface for nushell. As of the last few updates, the script shipped with asdf simply throws a syntax error in nushell, as `def-env` is now an undefined symbol. Please merge asap.

**Review by jthegedus — APPROVED** [review]

**Comment by jthegedus** [comment]
@hyperupcall GitHub is not letting me modify the files in the PR to resolve the conflict (Fish version update), can you update this when you have the time? Thanks

**Review by jthegedus — APPROVED** [review]

**Comment by jthegedus** [comment]
Thanks

**Pull request merged**
