### PR TITLE
Update examples using subcommands

### LINKED ISSUE #645: Command consistency
Hi, I'm learning about `asdf` 👋

While I read the documentation, I am seeing similar versions of commands and not sure if they're just the same command with varying syntax or different commands, and it's kind of confusing.

Some examples are:

 - `asdf plugin-add` and `asdf plugin-list` (with a `-`)
 - `asdf plugin add` and `asdf plugin list` (with a ` `)

Perhaps instances of these can be combined/cleaned up (or clarified) in the next minor release?

### PR DESCRIPTION
**Pull request by jsejcksn**
Replace references to aliases in the form of `command-subcommand` with `command subcommand`

Resolves #645

### CODE REVIEW

**Comment by jsejcksn** [comment]
@vic I did searches for

 - `plugin-add`
 - `plugin-list`
 - `plugin-remove`
 - `plugin-update`

in `.md` files (skipping [`CHANGELOG.md`](https://github.com/asdf-vm/asdf/blob/94db44b2596e1be7a1b4a7da0456838b7f966a19/CHANGELOG.md),  [`DEPRECATED_README.md`](https://github.com/asdf-vm/asdf/blob/94db44b2596e1be7a1b4a7da0456838b7f966a19/docs/DEPRECATED_README.md), and [`plugins-create.md`](https://github.com/asdf-vm/asdf/blob/94db44b2596e1be7a1b4a7da0456838b7f966a19/docs/plugins-create.md)). I don't know enough about creating plugins to know which `list-all` instances can be safely replaced with `list all`.

**Comment by vic** [comment]
@jsejcksn You can replace all `list-all` for `list all`, both are equivalent.

Thanks for updating the docs!

**Comment by jsejcksn** [comment]
@vic I think it's done. The only remaining `list-all` references I see are to the `bin/list-all` script

**Comment by vic** [comment]
@jsejcksn Nice, thank you for checking.

**Pull request merged**
