### PR TITLE
docs: link to our community and place(s) for q&a

### PR DESCRIPTION
**Pull request by jthegedus**
# Summary

Add links to README and website sidebar to our preferred tools for Q&A and community. GitHub Issues and SO links, GitHub Discussions placeholder.

Fixes: #766 

## Other Information

Re community: from the members who participated in https://github.com/asdf-vm/asdf/issues/766 it seems [GitHub Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/) will be the best place to keep community interaction as it doesn't introduce another tool (eg Discord) where conversations are hidden, not index-able by Google etc. I am open to further discussion on this, though vote for GitHub Discussions.

### CODE REVIEW

**Comment by jthegedus** [comment]
Screenshot of new sidebar:

image

I'm not sure if we should collapse Contributing and Community & Questions into one section or not. Thoughts?

**Comment by danhper** [comment]
Should we maybe wait for discussions to actually be available before merging this?

**Comment by jthegedus** [comment]
Perhaps. The initial Issue was more that we weren't taking a stance on any of the available tools and with the Discord re-brand a lot of programming communities are popping up there. This would signal our intent, though I can understand the confusion.

Maybe I shall remove (comment it out) in the side and README, and should someone ask again we can point them to #766 , would that be a good compromise?

**Comment by danhper** [comment]
This sounds good to me, as it is very unclear when we will have access to discussions.

**Pull request merged**
