### PR TITLE
Update no plugin installed error message

### PR DESCRIPTION
**Pull request by aaronjensen**
# Summary

Fixes: Updates error message when no plugins are installed

## Other Information

The previous error message was overly informal

### CODE REVIEW

**Review by jthegedus — APPROVED** [review]
While informal, some character shouldn't hurt, no?

**Comment by aaronjensen** [comment]
@jthegedus it made me waste time trying to figure out if I hit some sort of debug message, for one. 

There are other reasons it can do harm but I don’t feel strongly enough about it to wade into it on someone else’s project. If the maintainer wants to close this out because they value what you described as “character” then I won’t mind.

**Comment by jthegedus** [comment]
If it caused you to waste time, then that is not ideal.

**Comment by aaronjensen** [comment]
Thank you for the merge, I appreciate it.

**Pull request merged**
