### PR TITLE
docs: improve promotion of git install method

### PR DESCRIPTION
**Pull request by devinrhode2**
This can generally avoid complications due to installing under a package manager (homebrew, etc).

Related: https://github.com/asdf-vm/asdf/issues/1387

### CODE REVIEW

**Comment by jthegedus** [comment]
Hi @devinrhode2

I was intending on making a change like this. I was actually going to propose we go a step further and have an Official and All methods section, this way we can put the `git` method twice. I don't want people to skip to the table instead of reading and just grab `homebrew` as the top item in the table, so was going to propose `git` in the table as well as featured prominently above.

Eg:

**Comment by jthegedus** [comment]
Also, I need to fix the automation of the version change in the docs, so would prefer to leave it as the older one here so I can validate that.

**Comment by jthegedus** [comment]
I updated this PR with my preferred suggested example 1 whereby we separate Official & Community download/install methods.

**Comment by jthegedus** [comment]
@devinrhode2 Do you think this change will cover what you were initially concerned with?

@Stratus3D does this look okay to you? I think this might be enough to resolve #1366

**Comment by devinrhode2** [comment]
Sorry to not have a lot of detail here, but it looks great

There is the bug related to sudo-less homebrew, probably more important than doc tweaking

**Review by jthegedus — APPROVED** [review]
@Stratus3D I am merging as I have tested thoroughly locally and we can always iterate on the docs. If there are issues after it deploys I will hotfix.

Edit: everything worked fine, no need to hotfix or anything.

**Comment by Stratus3D** [comment]
Looks great @devinrhode2 and @jthegedus ! Sorry for the late review here.

**Pull request merged**
