### PR TITLE
Temp feature delimiter

### PR DESCRIPTION
**Pull request by botp**
Is your feature request related to a problem? Please describe

Currently "asdf list" command generate output that is intended to be read by humans (see some issues discussed here #(762)). This feature allows an option to render output that is friendly to scripts by "delimiting" the columns.  Option is specified using "-d" or "--delimited" with an accompanying "delimiter" value which can be any text, default is a space (see also updated help).  Output also comes pristine without headers then.

Eg,
`
$ asdf list -d
elixir 1.14.3 *
erlang 25.2.3 *
golang 1.19.4 *
nodejs 16.19.0 *
ruby 2.7.7 
ruby 3.1.3 
ruby 3.2.1 *
ruby mruby-3.2.0 
rust stable *

$ asdf list ruby -d
ruby 2.7.7 
ruby 3.1.3 
ruby 3.2.1 *
ruby mruby-3.2.0 

$ asdf list ruby 3 -d
ruby 3.1.3 
ruby 3.2.1 *

$ asdf list -d ":"
elixir:1.14.3:*
erlang:25.2.3:*
golang:1.19.4:*
nodejs:16.19.0:*
ruby:2.7.7:
ruby:3.1.3:
ruby:3.2.1:*
ruby:mruby-3.2.0:
rust:stable:*

$ asdf list --delimited "(--)"
elixir(--)1.14.3(--)*
erlang(--)25.2.3(--)*
golang(--)1.19.4(--)*
nodejs(--)16.19.0(--)*
ruby(--)2.7.7(--)
ruby(--)3.1.3(--)
ruby(--)3.2.1(--)*
ruby(--)mruby-3.2.0(--)
rust(--)stable(--)*
`

### CODE REVIEW

**Comment by botp** [comment]
omg, i think i f***up bigtime by including other commits. sorry. my very bad. only the first 2 (latest) commits are needed.

**Comment by botp** [comment]
i think i messed up by having 3 copies of the repo here.  even the merge was included. i'd like to clean it up or delete the whole pr but i think i cannot delete it/them. sorry again.

**Comment by jthegedus** [comment]
Probably best to just close this PR and open a new one once you've got it sorted.

**Comment by jthegedus** [comment]
Having said that, we want to support a global flag for output intended for machines. We haven't started work on this yet. You can see the prior discussion for this in https://github.com/asdf-vm/asdf/issues/1291

We will likely not merge this feature. If we support machine readable output we will be prescriptive of the format, not allowing users to configure the format like you have described.

**Pull request closed without merging**
