### PR TITLE
Shims remove on latest version uninstall (depends on #122)

### LINKED ISSUE #67: Plugin uninstall does not remove that plugin's shims
**Steps to reproduce**

```
$ asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
$ asdf install ruby 2.3.1
$ asdf global ruby 2.3.1
$ gem install bundler
$ asdf plugin-remove ruby
$ bundle
No such plugin
```

**Observed behavior**

Removing a plugin, leaves it's shims in the asdf shims directory, which leaves them polluting my PATH.

**Expected behavior**

When removing a plugin, all it's shims are removed as well. Calling bundle should give a "command not found" error.

### PR DESCRIPTION
**Pull request by vic**
When the latest version of a tool is uninstalled,
Remove the plugin shims (marked with metadata at #122)

Also found lots of missing tests and added them.

Closes #67

### CODE REVIEW

**Comment by tuvistavie** [comment]
@vic Thanks for this feature!
I think we should also remove the shims on `plugin-remove`, wdyt?

**Comment by vic** [comment]
@tuvistavie yes we should. I'll rebase with master and implement on `plugin-remove`

**Comment by vic** [comment]
@tuvistavie done, PR is ready.

**Comment by tuvistavie** [comment]
Great, thank you, I think we can merge this!
@asdf-vm/maintainers Seems good?

**Comment by Stratus3D** [comment]
Looks good to me! I'm always happy when a PR includes more tests 😄 

It will probably be a good idea to tag the 0.2.1 release after this is merged, since we've had quite a few fixes recently.

**Comment by Stratus3D** [comment]
I think this is a pretty safe PR, so I'm going to merge now.

**Pull request merged**
