### PR TITLE
chore: improve checkstyle double equals test regex & types

### PR DESCRIPTION
**Pull request by hyperupcall**
# Summary

General fixes for `checkstyle.py`, including a false positive fix for the `no-test-double-equals` rule.

### CODE REVIEW

**Comment by jthegedus** [comment]
If this change fixes a false positive, why does the lint script not show so in the PR checks?

**Comment by eankeen** [comment]
@jthegedus If I am understanding you correctly, the PR checks don't change because no existing code in `main` is matched by the old regular expression. Code from #1456 does match though (in particular, the `[ ${line[0]} == 'usage: '* ]`).

**Comment by hyperupcall** [comment]
@jthegedus If I am understanding you correctly, the PR checks don't change because no existing code in main is matched by the old regular expression. Code from https://github.com/asdf-vm/asdf/pull/1456 does match though (in particular, the [ ${line[0]} == 'usage: '* ]).

**Comment by jthegedus** [comment]
I thought the Workflows executed from the forked code, not what was on the target branch. https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

Which would lead me to think that this change hasn't matched any previous false positives.

**Comment by hyperupcall** [comment]
@jthegedus I don't think we are in disagreement - this change doesn't match any _previous_ false positives, but it will address potential _future_ potential ones ones. Specifically, the false positives are shown in the CI errors of #1456, which yes are executed from the forked code. I think we agree that these changes will fix false positives?

Maybe it's weird that I introduced this fix separately instead of bundling it together with #1456? I'm not sure

**Comment by Stratus3D** [comment]
@hyperupcall I think I understand. As you say the false positive wasn't present in the codebase (since the wrong regex in this `checkstyle.py` script would have prevented it from ever being added).

@jthegedus you can validate this by reverting the change to line 125/old line 118 in `checkstyle.py` and running the file's tests like this: `./scripts/checkstyle.py --internal-test-regex`. It'll print this:

```
no-test-double-equals: Failed negative test:
=> [[ "${lines[0]}" == 'usage: '* ]]
```

**Review by Stratus3D — APPROVED** [review]
Code seems fine but it's not clear to me why this check is needed at all.

The description states: `Although it is valid Bash, it reduces consistency and copy-paste-ability`. Is that all there is too it?

**Comment by hyperupcall** [comment]
The check was originally added to help address #1313. Maybe the error message should change to be more descriptive?

**Comment by jthegedus** [comment]
Much better error msg, thanks!

**Pull request merged**
