### PR TITLE
feat: add plugin location when update the plugin

### PR DESCRIPTION
**Pull request by edvardsanta**
It is a feature created by recommendation of issue 1573.

# Summary
Display plugin location when calling plugin update 
``` shell
❯ asdf plugin-update ruby
Plugin ruby location: /home/user/.asdf/plugins/ruby
Updating ruby to master
Already on 'master'
Your branch is up to date with 'origin/master'.
```
Closes: #1573

Currently that is just 
```shell
❯ asdf plugin-update ruby
Updating ruby to master
Already on 'master'
Your branch is up to date with 'origin/master'.
```

### CODE REVIEW

**Comment by edvardsanta** [comment]
## Observation:
In the test code, i tried to implement get_full_path to check the output with expected output , the get_full_path function in the test appears to be returning only the plugin name instead of the full path to the plugin. I don´t know if it is the expected behavior

**Comment by hyperupcall** [comment]
I don't see any `get_full_path` function, but `get_plugin_path` seems to work for me:

```bash
@test "asdf plugin-update prints the location of plugin (specific)" {
  local plugin_path
  plugin_path="$(get_plugin_path dummy)"

  run asdf plugin-update dummy

  local expected_output="Plugin dummy location: $plugin_path"
  [[ "$output" == *"$expected_output"* ]]
}
```

```text
...
 ✓ asdf plugin-update prints the location of plugin (specific)
```

**Comment by hyperupcall** [comment]
LGTM, my only comment is that the wording might be a little confusing - perhaps `"Location of 'ruby' plugin: "` would fit better?

**Comment by hyperupcall** [comment]
Unfortunately, I cannot run the GitHub actions test workflow, but I have ran locally and it seems there a few other failing tests such as `asdf plugin-update executes configured pre hook (generic)`.

It looks like current tests don't take into account that this can be printed first. It looks like adding an asterisk to the glob test fixes things:

```sh
[[ "$output" = *"UPDATE dummy"*"${expected_output}" ]]
```

**Comment by edvardsanta** [comment]
Thanks for your suggestions, i will resee my code and check the tests this week

**Comment by edvardsanta** [comment]
I did the changes, thanks for your help. I am  trying to figure out  why the other tests are failing, I tried removing my piece of code, but it's still not working

image

**Comment by hyperupcall** [comment]
Hmm, I only get the same error as before:

```txt
✗ asdf plugin-update executes configured pre hook (specific)
   (in test file test/plugin_update_command.bats, line 188)
     `[[ "$output" = "UPDATE"*"${expected_output}" ]]' failed

It might be an issue with your computer only . The `--print-output-on-failure` flag may help diagnosing the issue

**Comment by edvardsanta** [comment]
Hi, I made the changes according to what you said
image

**Comment by edvardsanta** [comment]
Hello, it was a simple change, is there any impediment or problem that I can solve for this pull request to be finished?

**Comment by hyperupcall** [comment]
@edvardsanta I'm not sure if you forgot to push your changes, I'm still getting the error:

```sh
$ bats test/plugin_update_command.bats --print-output-on-failure
plugin_update_command.bats
 ✓ asdf plugin-update should pull latest default branch (refs/remotes/origin/HEAD) for plugin
 ✓ asdf plugin-update should pull latest default branch (refs/remotes/origin/HEAD) for plugin even if default branch changes
 ✓ asdf plugin-update should pull latest default branch (refs/remotes/origin/HEAD) for plugin even if the default branch contains a forward slash
 ✓ asdf plugin-update should pull latest default branch (refs/remotes/origin/HEAD) for plugin even if already set to specific ref
 ✓ asdf plugin-update should not remove plugin versions
 ✓ asdf plugin-update should not remove plugins
 ✓ asdf plugin-update should not remove shims
 ✓ asdf plugin-update done for all plugins
 ✓ asdf plugin-update executes post-plugin update script
 ✓ asdf plugin-update executes post-plugin update script if git-ref updated
 ✓ asdf plugin-update executes configured pre hook (generic)
 ✗ asdf plugin-update executes configured pre hook (specific)
   (in test file test/plugin_update_command.bats, line 188)
     `[[ "$output" = "UPDATE"*"${expected_output}" ]]' failed
   Last output:
   Location of dummy plugin: /tmp/asdf with spaces.9nU1/home/.asdf/plugins/dummy
   UPDATE
   Updating dummy to master
   Already on 'master'
   Your branch is up to date with 'origin/master'.
   plugin updated path=/tmp/asdf with spaces.9nU1/home/.asdf/plugins/dummy old git-ref=b809aa8 new git-ref=b809aa8
 ✓ asdf plugin-update executes configured post hook (generic)
 ✓ asdf plugin-update executes configured post hook (specific)
 ✓ asdf plugin-update prints the location of plugin (specific)

15 tests, 1 failure
```

**Comment by edvardsanta** [comment]
this test is failing even without, my feat, but i will try to figure out what is happening, thx

**Comment by hyperupcall** [comment]
Checked the diff and I believe the test suite will pass fully. I can't merge your PR here, but I'll cherry-pick and squash your commits (and some from other existing PRs) into [my fork](https://github.com/fox-incubating/asdf) and make a release later today.

**Review by jthegedus — APPROVED** [review]
Thanks! And thanks for the review @hyperupcall

**Pull request merged**
