### PR TITLE
Install the latest version when running tests

### PR DESCRIPTION
**Pull request by tuvistavie**
I had issues installing Python latest version, so I think running the CI on the latest
version will help.
I will eventually ask Travis to enable cron jobs for each language repositories.

https://docs.travis-ci.com/user/cron-jobs/

### CODE REVIEW

**Comment by tuvistavie** [comment]
Oh, after checking Elixir, the latest version is the first in the versions array.
I think the order should be consistent for all plugins, so maybe we could sort the array directly
in asdf rather than in the plugin, what do you think?

**Comment by HashNuke** [comment]
@tuvistavie 👍
Yes we could move the sorting to asdf itself instead of doing it in the plugins. Will bring some uniformity.

**Comment by tuvistavie** [comment]
Ok, so let's close this PR and sort the versions from the latest to the oldest! :+1:

**Comment by Stratus3D** [comment]
@tuvistavie The problem is this doesn't handle language-specific quirks or semantic versioning properly. Here is an example (this code isn't the same as what's in the PR, but it's using `sort`):

    array=("1.20.1" "1.5.1" "1.1.1")
    sorted=$(sort <<<$array)
    # Output
    1.1.1
    1.20.1
    1.5.1

Clearly these versions are not sorted properly. Since this is semantic versioning 1.20.1 is the most recent version, but it's in the middle of the list, between 1.1.1 and 1.5.1, which are both older.

There are other versioning quirks, like versioning method changes (Erlang was using it's own versioning system until version 17, when they switched to semantic versioning). I think having plugins sort there own versions is the safest method, and it allows us to handle inconsistencies when we need to.

**Comment by Stratus3D** [comment]
Also, this was discussed here: https://github.com/asdf-vm/asdf/issues/33

**Comment by HashNuke** [comment]
@Stratus3D OTP-like versions is one thing that bothers me. Since those versions are now past, any other software not following semantic versioning?

I'm now split between choices.

B/w I just found out that `sort -V` will do semantic version sorting. But the `-V` option isn't available on the OSX version of sort.

**Comment by tuvistavie** [comment]
@Stratus3D @HashNuke Thanks for the feedback.

I agree it is maybe better to handle this in each plugin.
For my Python plugin, I thing I am going to use

```
    local sort_cmd
    if sort --help | grep -q -- '-V'; then
        sort_cmd='sort -r -V'
    else
        sort_cmd='sort -r'
    fi
```

for now.
Maybe we can implement something to sort semantic versions later.

**Comment by Stratus3D** [comment]
@tuvistavie I'll update my Lua plugin as well.

**Pull request closed without merging**
