### PR TITLE
Add support for local and global commands.

### PR DESCRIPTION
**Pull request by tuvistavie**
I implemented what I talked to you about on Twitter.
https://twitter.com/tuvistavie/status/722089523916591104

I borrowed the `global` and `local` from rbenv/pyenv, but if you have any better suggestion
for the command names I am of course completely open.

### CODE REVIEW

**Comment by HashNuke** [comment]
I think we'll need an update to read from legacy file if the option is enabled.

**Comment by ericmj** [comment]
I can't seem to find anything that documents the different between local and global. When I run them they seem to do the exact same thing.

**Comment by tuvistavie** [comment]
@ericmj Sorry for that, it seems I introduced a bug [here](https://github.com/asdf-vm/asdf/commit/b0513a6da075ac356752fe4afad68c65c9d1bd1b) :sweat: 
I just pushed a fix to master, please try to update.

**Comment by ericmj** [comment]
Thank you. Could you also add documentation about what it does?

**Comment by tuvistavie** [comment]
Just added this to the README!

**Comment by ericmj** [comment]
:heart:

**Pull request merged**
