### PR TITLE
fix: enforce consistent shell redirection format

### PR DESCRIPTION
**Pull request by hyperupcall**
# Summary

Make redirections more consistent

### CODE REVIEW

**Comment by jthegedus** [comment]
I have no objection to this change. I would like to get @Stratus3D opinion.

**Comment by jthegedus** [comment]
>@hyperupcall &> isn't POSIX is it? I assume we can only enforce this on Bash files.

I guess if it isn't, we would just want to ensure `checkstyle.py` only asserts/fixes this rule for `.bash` files.

**Comment by jthegedus** [comment]
> so this new rule only applies to our POSIX shell files

@hyperupcall Do you mean non-POSIX? We want to apply this to `.bash` and NOT `.sh`, right?

Sorry, I am getting confused.

**Comment by hyperupcall** [comment]
@jthegedus My apologies, that was me - fixed

**Comment by Stratus3D** [comment]
@jthegedus you can merge whenever you are ready.

**Pull request merged**
