### PR TITLE
add part of asdf backronym. the important part.

### PR DESCRIPTION
**Pull request by burnettk**
enjoy!

### CODE REVIEW

**Comment by sql-sith** [comment]
Is there an actual acronym or backronym? I've been wondering about why this project is called **asdf**, especially since LISP already had an ASDF acronym meaning "Another System Definition Facility."

**Comment by vic** [comment]
https://www.urbandictionary.com/define.php?term=asdf

`Asdf just is. Do not question the almighty power of asdf`

**Comment by jthegedus** [comment]
Sorry for causing the conflict, the new README and docs site is live! http://asdf-vm.github.io/asdf/#/

**Comment by danhper** [comment]
This has been inactive for quite a while now, so I will close.
I am not sure there is currently any acronym or bacrkonym for asdf.
If you would like to discuss the name or backronym, please open an issue.

**Pull request closed without merging**
