### PR TITLE
fix: Remove usage of `$(pwd)` in favor of `$PWD`

### PR DESCRIPTION
**Pull request by hyperupcall**
As mentioned in the `checkstyle.py`, using the former increases execution time as a subshell has to be constructed. `pwd` being a builtin helps, but we can do better.

As suggested [here](https://github.com/asdf-vm/asdf/pull/1385#discussion_r1054018600), I added a way to validate the regular expressions

### CODE REVIEW

**Comment by hyperupcall** [comment]
Rebased to make the same fix as #1409

**Comment by jthegedus** [comment]
As per the conversation from #1409, this would qualify as a `fix:` as it makes code changes to the core of asdf.

**Review by jthegedus — APPROVED** [review]
@Stratus3D I know we discussed in the other PRs to rewrite this python script in Bash, and I am still all for that, but in the meantime feel we should merge this as it immediately improves the codebase.

**Review by Stratus3D — APPROVED** [review]

**Review by Stratus3D — CHANGES_REQUESTED** [review]
It appears the checkstyle.py check is now failing due to the permission being changed on the file. If you can fix @hyperupcall I'll get this merged.

**Comment by Stratus3D** [comment]
Looks like I was the one who broke permissions on the file. I updated and merge the PR. Thanks @hyperupcall !

**Pull request merged**
