### PR TITLE
Prepare for 0.2.0 release

### PR DESCRIPTION
**Pull request by Stratus3D**
* Add everything that was merged for 0.2.0 to the changelog.
* Update install command in the readme with 0.2.0 tag.

I will tag 0.2.0 when I merge this.

Let me know there are any issues with merging this.

### CODE REVIEW

**Comment by tuvistavie** [comment]
LGTM!! :smile:

**Comment by HashNuke** [comment]
@Stratus3D I think we should some how merge this ourselves https://github.com/asdf-vm/asdf/pull/96 and then make a release. I'll sort this PR in the next couple days by hand.

**Comment by Stratus3D** [comment]
@HashNuke I created a PR that includes that fix, as well as a test for the install command in a directory that contains whitespace - #104.

**Comment by HashNuke** [comment]
@tuvistavie @Stratus3D 💯

**Comment by Stratus3D** [comment]
Just tagged 0.2.0.

**Pull request merged**
