### PR TITLE
Use source instead of dot alias

### PR DESCRIPTION
**Pull request by mijailr**
# Summary

Some users not familiarized with bash or the shell at all are having issues following the installation process, specifically with the dot builtin `source` .

Using source it's more clear they need to copy the whole line.

```diff
- . $HOME/.asdf/asdf.sh
+ source $HOME/.asdf/asdf.sh
```

### CODE REVIEW

**Comment by jthegedus** [comment]
Thanks for raising, perhaps we should explain this in the docs.

The reason for using `.` over `source` is that `.` is the POSIX standard for this syntax and therefore more exportable to other shells. Where possible we're preferring PSOSIX compatible code.

**Comment by Stratus3D** [comment]
@jthegedus would it make sense to add `source` to our banned commands list?

**Comment by jthegedus** [comment]
I think we should z then it's at least documented somewhere

**Comment by mijailr** [comment]
Oh I see thanks for the clarification.

**Pull request closed without merging**
