### PR TITLE
Which command

### LINKED ISSUE #72: [Proposal] Command to get direct path of the binary
We need a way to expose the path to a binary. For example to debug with `gdb`, we need the direct path of the `ruby` binary and not the shim.

Something like

```
$ asdf bin ruby
/Users/HashNuke/.asdf/installs/ruby/2.3.0/bin/ruby
```
#### As a tangential discussion

Do we rename `asdf which` command to `asdf version` OR `asdf current` instead?

That way this can be in like with the unix `which` command. So we can use `asdf which ruby`

```
# this is currently what the asdf-which command does
# proposing to change it to asdf-current instead
$ asdf current ruby
2.3.0

# and use asdf-which to return the full path of the binary
$ asdf which ruby
/Users/HashNuke/.asdf/installs/ruby/2.3.0/bin/ruby
```

### PR DESCRIPTION
**Pull request by fcrespo82**
Hi guys, this is my attempt to do the which command it fixes #72 and #150.

I guess it could be better when returning the main binary, but I think would need a Plugin API change.

Hope it helps!

### CODE REVIEW

**Comment by tuvistavie** [comment]
Thank you very much, and sorry for the delay.
I will try the branch locally, and let you know if I run into any issue.
If you get a moment, could you rebase on top of master as it seems we introduced some changes to `completions/asdf.bash` at some point.
Again, thank you :smiley:

**Comment by fcrespo82** [comment]
Hi @tuvistavie, just updated the branch with the changes to `completions/asdf.bash`.
It should be able to merge without conflicts now.
Thank you.

**Comment by Stratus3D** [comment]
Thanks @fcrespo82 ! Sorry it took so long to merge this.

**Comment by Stratus3D** [comment]
It would be nice if we could pass any arbitrary name to this command. For example:

```
$ asdf which ruby
/home/trevor/.asdf/installs/ruby/2.3.0/bin/ruby
$ asdf which irb
No such plugin
```
It would be better if the second command returned `/home/trevor/.asdf/installs/ruby/2.3.0/bin/ruby`.

**Pull request merged**
