### PR TITLE
Update getting-started.md - branch v0.14.0 does not exist

### PR DESCRIPTION
**Pull request by fcbry**
Update getting-started.md - branch v0.14.0 does not exist

### CODE REVIEW

**Comment by Stratus3D** [comment]
Hi @fcbry, the instructions are correct, at least for recent versions of Git.

> -b <name>
> --branch <name>
>
>    Instead of pointing the newly created HEAD to the branch pointed to by the cloned repository’s HEAD, point to <name> branch instead. In a non-bare repository, this is the branch that will be checked out. --branch can also take **tags and detaches the HEAD at that commit in the resulting repository.**

-- from https://git-scm.com/docs/git-clone

The Git flag is poorly named, but we instruct the user to pass in the tag via the `--branch` option, which is valid.

**Comment by fcbry** [comment]
@Stratus3D - I mean the branch doesn't exist, and there is a different branch referenced in the japanese docs

**Comment by Stratus3D** [comment]
@fcbry it's not a branch it's a tag.

**Comment by fcbry** [comment]
My appologies, I skimmed your response and failed to pick up on the rather obvious and correct point:
>> The Git flag is poorly named, but we instruct the user to pass in the tag via the --branch option, which is valid.
😊

**Pull request closed without merging**
