### PR TITLE
begin stabalising asdf prepending to PATH logic

### PR DESCRIPTION
**Pull request by jthegedus**
# Summary

as per suggestion from here - https://github.com/asdf-vm/asdf/pull/303#issuecomment-371231967 :
* remove colon from `ASDF_` variables
* use `:` to normalize PATH
* match against whole `ASDF_` PATH segments
* add `:` back to string replacement - this still doesn't match against asdf segments when last in PATH
* add `:` back to asdf/PATH merging as it's no longer in the `ASDF_` vars

## Other Information

This fix is a stopgap to address the more serious problems (matching partial segments) raised in https://github.com/asdf-vm/asdf/pull/303#issuecomment-371231967 . I plan to address the rest of the issues is another PR with tests for each edge case.

### CODE REVIEW

**Comment by jthegedus** [comment]
@gohanlon it would be good to get your eyes on this too before it goes through.

**Comment by gohanlon** [comment]
Looks good to me!

**Comment by jthegedus** [comment]
Cheers all :smiley:

**Comment by Stratus3D** [comment]
Just tagged a new version that includes all these fixes - https://github.com/asdf-vm/asdf/blob/master/CHANGELOG.md

**Pull request merged**
